; Override for build phase on Vercel
extension_dir = "${PHP_INI_EXTENSION_DIR}"
; Tắt hoàn toàn việc hiển thị lỗi ra màn hình
display_errors = Off

; Đặt mức báo cáo lỗi thành không
;error_reporting = E_ALL & ~E_WARNING & ~E_NOTICE
